# Generated by Django 4.0 on 2022-02-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guitar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('guitar_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=200)),
                ('image', models.FileField(default='guitar.jpg', upload_to='guitar')),
            ],
            options={
                'db_table': 'guitar',
            },
        ),
    ]
