# Generated by Django 4.0 on 2022-02-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'booking',
            },
        ),
    ]
